name: Node.js CI

on:
  push:
    branches: [dev]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          password: ${{ secrets.CD_PASSWORD }}
          port: 22
          script: |
            cd ~/home/danielwetan/apps/node1
            git pull origin master
            git status
            npm install --only=prod
            pm2 restart node1
